export { default as AuthRoutes } from "./auth-routes"
export { default as DashboardRoutes } from "./dashboard-routes"
export { default as EmployeeAppraisalRoutes } from "./employee-appraisal-routes"
export { default as KRAsRoutes } from "./kra-routes"
export { default as SettingsRoutes } from "./settings-routes"
export { default as TasksRoutes } from "./tasks-routes"